### PR TITLE
Fixes to compile on ghc-9.2.4

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by L-as** [comment]
I'm coincidentally working on the exact same thing! Is IOG trying to upgrade to 9.2.4?

**Comment by L-as** [comment]
FWIW I have some work in progress that removes the cardano-prelude dependency (but not cardano-prelude-test)

**Comment by lehins** [comment]
> FWIW I have some work in progress that removes the cardano-prelude dependency (but not cardano-prelude-test)

@L-as you might want to coordinate with @teodanciu, just so we can avoid duplicate work. See WIP #2992

**Comment by L-as** [comment]
Thank you, seems like a lot of duplicate work is already ongoing though :)

**Comment by angerman** [comment]
Closed in favour of https://github.com/input-output-hk/cardano-ledger/pull/3041 for now. We'll still need a back port of that.

**Pull request closed without merging**
