### PR TITLE
CAD-1765 missing imports

### PR DESCRIPTION
**Pull request by CodiePP**
was not able to compile release-1.19.1 using "stack" due to missing imports

### CODE REVIEW

**Comment by nc6** [comment]
As you can see, adding these imports in causes our CI to fail due to warnings... I have no idea why stack thinks they're needed. I can only assume it's using a different version of a library somewhere that was otherwise exporting these. Are we using the same version of `cardano-prelude` - that would be the obvious candidate

**Comment by mrBliss** [comment]
> As you can see, adding these imports in causes our CI to fail due to warnings... I have no idea why stack thinks they're needed. I can only assume it's using a different version of a library somewhere that was otherwise exporting these. Are we using the same version of `cardano-prelude` - that would be the obvious candidate

`cardano-prelude` is based on `protolude`. I think the Stack problem is probably due to a different version of `protolude` being used for the Stack build than for the Cabal build. There are no bounds specified in `cardano-prelude.cabal` on the `protolude` dependency.

In the Stack snapshot that `cardano-prelude` (and all downstream repos) use(s), `protolude-0.2.3` is used. You can see this by searching for `protolude` on https://www.stackage.org/lts-13.26.

According to the `cabal-plan` tool, Cabal uses `protolude-0.3.0` to build this repo and the other downstream ones. I suspect that `protolude-0.3.0` no longer re-exports `typeOf` and `isAscii`.

So I agree with Nick that *adding the imports here is not the right solution*.

Instead, we should:
* Add lower and upper bounds in `cardano-prelude.cabal` on the `protolude` dependency. Note that we **want at least `protolude-0.3.0`**, because that's the first version compatible with GHC 8.10. Going back to 0.2.3 or 0.2.4 would be stupid, as that would block our switch to GHC 8.10.
* **Add `protolude-0.3.0` to `stack.yaml`**. Clearly not in this repo, as there is no `stack.yaml`, but in the repo you want to build with Stack.

**Comment by nc6** [comment]
Note that in the short term this can be fixed solely with the second point.

**Comment by CodiePP** [comment]
I am trying this out. Thanks for the pointers.

**Pull request closed without merging**
