### PR TITLE
Allow CommitteeHotKey to be ScriptHash

### LINKED ISSUE #3509: Allow Constitutional Committe hot key to be a script hash
Current implementation only allows KeyHashes for Constitutional Committee hot keys, but there seems to be a desire to use scripts for constitutional committee members, so we need to change the

* `ConwayAuthCommitteeHotKey`
* And `VotingProcedure` (in progress in #3508)

### PR DESCRIPTION
**Pull request by aniketd**
# Description

Resolves #3509 

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Comment by Soupstraw** [comment]
You'll also have to add this to the `scriptWitsVKeyNeeded` calculation

**Comment by Soupstraw** [comment]
Sorry, I meant to say `scriptsNeeded`, since scripts don't have witnesses :s

**Review by lehins — APPROVED** [review]
Just needs a rebase on master and some conflict fixes. Otherwise looks good

**Comment by aniketd** [comment]
@Soupstraw I may be mistaken but it looks like `getConwayScriptsNeeded` already accounts for these credentials by the use of `credScriptHash` on the `CommitteeVoter`? Please correct me if this is not the case.

**Comment by Soupstraw** [comment]
> @Soupstraw I may be mistaken but it looks like `getConwayScriptsNeeded` already accounts for these credentials by the use of `credScriptHash` on the `CommitteeVoter`? Please correct me if this is not the case.

yeah, looks good

**Review by lehins — APPROVED** [review]
Looks great. Thank you!

**Pull request merged**
