### PR TITLE
Update to a more recent Plutus repo version

### PR DESCRIPTION
**Pull request by sjoerdvisscher**

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
Hi, @redxaxder, I've been told you can help me with these test failures: https://hydra.iohk.io/build/6694998/nixlog/1 Do you know what's going on?

**Comment by michaelpj** [comment]
To add some detail there: this PR updates to a version that includes the `Data` serialization code that you wrote, which makes us think this might be related.

(Note that we do also have some round-tripping tests for serializing `Data`, which did pass, but possibly our generator isn't as good as yours!)

**Comment by redxaxder** [comment]
> Hi, @redxaxder, I've been told you can help me with these test failures: https://hydra.iohk.io/build/6694998/nixlog/1 Do you know what's going on?

The failure was here:
```
      D8 66             # tag(102)
         81             # array(1)
            21          # negative(1)  <- expected word
```

We failed to decode a constructor with a negative tag. My commit changes the generator to only create non-negative tag values. 

With the restrictions we've recently introduced to the wire format it might make sense to change the definition of `Data` to match.

From this:
```
data Data =
      Constr Integer [Data]
    | [...]
```
To something like this:
```
data Data =
      Constr Word64 [Data]
    | [...]
```

**Comment by michaelpj** [comment]
That _would_ make total sense except that then the Plutus Tx compiler will choke on it since it only knows about `Integer`. So either we'd need another parallel type or to add an unsigned integral type. For now, I'd prefer to just accept that we are allowing the representation of some invalid states here.

**Pull request closed without merging**
