### PR TITLE
Cleaning up bootstrap witness stuff

### PR DESCRIPTION
**Pull request by redxaxder**

### CODE REVIEW

**Review by uroboros — APPROVED** [review]
👍

**Review by dcoutts — APPROVED** [review]
Thanks, the makeBootstrapWitness should be useful in the cardano-api package

**Comment by nc6** [comment]
This is worrying:

```
    total amount of Ada is preserved:                                        FAIL (75.83s)
      *** Failed! Falsified (after 11 tests and 1 shrink):
```

**Comment by uroboros** [comment]
> This is worrying:
> 
> ```
>     total amount of Ada is preserved:                                        FAIL (75.83s)
>       *** Failed! Falsified (after 11 tests and 1 shrink):
> ```

agreed, I'm testing this locally with more detailed tracing, watch this space...

**Comment by uroboros** [comment]
> > This is worrying:
> > ```
> >     total amount of Ada is preserved:                                        FAIL (75.83s)
> >       *** Failed! Falsified (after 11 tests and 1 shrink):
> > ```
> 
> agreed, I'm testing this locally with more detailed tracing, watch this space...

**Comment by uroboros** [comment]
my apologies, closed this by mistake

**Comment by redxaxder** [comment]
> This is worrying:

It sure is!

**Pull request merged**
