### PR TITLE
Minor improvement - introduce RawSeed

### PR DESCRIPTION
**Pull request by lehins**
I needed a small task just to get acquainted with the codebase, so I found a few minor improvements I could make while looking through the repo. One of which was adding `RawSeed` instead of a 5-tuple of `Word64`s.
I am totally fine with discarding this PR, since it was more of an exercise to build the project and verify my new tooling and dev setup works fine. (Couple files where reformatted with ordmolu, so diff is a bit bigger than I intended)

CC @JaredCorduan

### CODE REVIEW

**Review by nc6 — APPROVED** [review]
LGTM

**Comment by nc6** [comment]
However, looks like there's some tests in various places that still need to be updated.

**Comment by lehins** [comment]
> However, looks like there's some tests in various places that still need to be updated.

Have no idea how I missed these couple of modules. I thought I did build the whole project. In any case, I finished the update.

**Review by JaredCorduan — APPROVED** [review]
Looks great to me!

**Comment by JaredCorduan** [comment]
@lehins buildkite isn't ever going to run for this PR since it is from a fork (which is preventing us from merging). But now you are in the organization, so you could push a branch.

**Comment by lehins** [comment]
Closed in favor of #2314 

> buildkite isn't ever going to run for this PR since it is from a fork (which is preventing us from merging)

It means that people from the community that aren't part of the organization can never contribute. That's odd for an open source project.

**Comment by JaredCorduan** [comment]
> Closed in favor of #2314
> 
> > buildkite isn't ever going to run for this PR since it is from a fork (which is preventing us from merging)
> 
> It means that people from the community that aren't part of the organization can never contribute. That's odd for an open source project.

indeed, I don't like it either. I would love to find a solution. In the past, I have cherry-picked the commits from community member PRs into a branch of my own, which is not a great solution.

**Comment by JaredCorduan** [comment]
@michaelpj had a great suggestion, IMHO: https://github.com/buildkite/feedback/issues/288#issuecomment-502739187

**Pull request closed without merging**
