### PR TITLE
MetaData -> Metadata

### PR DESCRIPTION
**Pull request by rvl**
Makes the spelling consistent.

```
git ls-files -z | xargs -0 sed -i -e 's/MetaData/Metadata/g' -e 's/MetaDatum/Metadatum/g'
rename MetaData Metadata `git ls-files '*.hs'`
```

### CODE REVIEW

**Comment by mrBliss** [comment]
Thanks! This was also driving me nuts :slightly_smiling_face:

**Comment by rvl** [comment]
No problem... can I leave this one with you guys?

**Comment by mrBliss** [comment]
Rebased and solved the ambiguity issues.

**Comment by JaredCorduan** [comment]
> No problem... can I leave this one with you guys?

yep, absolutely

thank you @mrBliss :) I can run ormolu and figure out why the latex builds are broken

**Review by JaredCorduan — APPROVED** [review]
=D

**Pull request merged**
