### PR TITLE
Minor improvements to cabal.project

### PR DESCRIPTION
**Pull request by kk-hainq**
Minor things I found while bumping dependencies elsewhere:
- Point flat back to its original repository (bug fix merged).
- Remove GHC options on removed packages.

### CODE REVIEW

**Review by nc6 — APPROVED** [review]

**Comment by JaredCorduan** [comment]
as always, thank you @kk-hainq for your help! I don't understand the hydra error, the log says "All 460 tests passed (1224.75s)". :thinking:

**Comment by kk-hainq** [comment]
@JaredCorduan I've rebased and it's gone now! The `ormolu` one seems stuck, but hopefully not required.

**Comment by JaredCorduan** [comment]
> @JaredCorduan I've rebased and it's gone now! The `ormolu` one seems stuck, but hopefully not required.

great, thanks again! the ormolu action is actually required, but I'll figure out what it takes to get past it

**Review by JaredCorduan — APPROVED** [review]

**Comment by JaredCorduan** [comment]
Actually, that ormolu check is the old one, and should not be required. The new ormolu check is inside the "Haskell CI" action, which I don't see in the list of checks.

it's as though https://github.com/input-output-hk/cardano-ledger/pull/2499/files never happened. which is weird, because your fork is up to date.

**Comment by kk-hainq** [comment]
@JaredCorduan I've faced odd CI situations on a few first PRs in other repositories as well. Can you help cherry-pick `43b1b4de603f520146f2aaa6f8cba27ed4c46f6d` to another branch and open a new PR for it? :(

**Comment by JaredCorduan** [comment]
> @JaredCorduan I've faced odd CI situations on a few first PRs in other repositories as well. Can you help cherry-pick `43b1b4de603f520146f2aaa6f8cba27ed4c46f6d` to another branch and open a new PR for it? :(

absolutely @kk-hainq ! The only reason I didn't do that immediately was because I wanted to learn what was going wrong so that accepting PRs from forks would be easy in the future. Which is the whole reason for https://github.com/input-output-hk/cardano-ledger/pull/2499/files But I'm more than happy to get this across the line and see what happens next time.

**Comment by kk-hainq** [comment]
Sure, thanks! I can hunt typos with my clones when you need more experiments...

**Comment by JaredCorduan** [comment]
replaced by #2600

**Pull request closed without merging**
