### PR TITLE
Avoid Double in JSON genesis parameter conversions

### PR DESCRIPTION
**Pull request by dcoutts**
We use Rational internally for many parameters (either directly or via
UnitInterval). We must be careful with conversions of fractional numbers
in JSON.

In particular if we convert a value like 0.1 via Double which cannot be
represented precisely then we end up with this:

> toRational (0.1 :: Double)
3602879701896397 % 36028797018963968

Rather than 1 % 10

So instead we must go from the Scientific type that Aeson uses, directly
to Rational or (Ratio Word64 for UnitInterval) without going via Double.

Before:
```
> Data.Aeson.eitherDecode "0.1" :: Either String UnitInterval
Right (UnsafeUnitInterval (3602879701896397 % 36028797018963968))
```

After:
```
> Data.Aeson.eitherDecode "0.1" :: Either String UnitInterval
Right (UnsafeUnitInterval (1 % 10))
```

### CODE REVIEW

**Comment by dcoutts** [comment]
This bug was causing the frequency of the BFT cycle to be too low. With f = 0.1, we would expect 1 in 10 BFT slots to contain a block, but it was actually 1 in 9. That's because as part of the calculation we do `floor (1 / f)` and so if f is not 0.1 but 0.100000000001 then the result is 9 not 10.

**Review by JaredCorduan — APPROVED** [review]
LGTM

**Comment by kderme** [comment]
failure in tests: "decentralisationParam\": 1.89999999999999995281552145343084703199565410614013671875e-2 vs  1.9e-2

**Review by kderme — APPROVED** [review]
lgtm. Some rounding errors are still possible, since `UnitInterval` is based on Word64 i.e.
```
realToFrac (1e-20 :: Scientific) :: Ratio Word64
1 % 7766279631452241920
```
but for very small numbers which probably will never appear. For common numbers `Scientific` does a better job than `Double`.

**Pull request merged**
