### PR TITLE
Fix typo in CDDL key name

### PR DESCRIPTION
**Pull request by SebastienGllmt**

### CODE REVIEW

**Review by uroboros — APPROVED** [review]

**Review by JaredCorduan — APPROVED** [review]
thank you @SebastienGllmt !

**Comment by JaredCorduan** [comment]
it seems that buildkite is hanging forever. perhaps due to a PR from a fork? sorry @SebastienGllmt , I can just push the patch myself if buildkite won't cooperate.

**Comment by JaredCorduan** [comment]
@SebastienGllmt turns out that we don't enable buildkite builds from 3rd party forks for security reasons. so we can just always grab your patches and push them ourselves. thanks again!

**Comment by JaredCorduan** [comment]
replaced by #1706

**Pull request closed without merging**
