### PR TITLE
Bump to use latest released cardano-base and cardano-prelude packages

### PR DESCRIPTION
**Pull request by michaelpj**
The release branch is using an unreleased commit of `cardano-base` which contains the SECP primitives but is before the `heapwords` split. This makes it incompatible with either of the released versions:
- The previous version doesn't have the SECP primitives
- The next version has the heapwords split

In order to make the release branch usable via CHaP, I think the simplest thing is to backport the changes for the newer `cardano-base` packages, i.e. the `heapwords` split. This is a bit tedious but not too bad overall.

Afterwards I'll release another version from this branch.

### CODE REVIEW

**Comment by michaelpj** [comment]
Hmm, I'm just going to double check this works, do not merge for now.

**Comment by JaredCorduan** [comment]
thank you @michaelpj !

**Comment by angerman** [comment]
@michaelpj why did you end up closing this PR and not pursuing it to be merged into 1.1.x?

**Comment by michaelpj** [comment]
Because I was told that 1.1.x was not a real release and anyway I was trying to fix `node@1.35` which was using `1.0.x` not `1.1.x` so I was doing completely the wrong thing anyway.

**Comment by angerman** [comment]
We'll use this as the basis for the 1.1.1 release, for use in https://github.com/input-output-hk/cardano-node/pull/4608.

Todo:
- [x] CI green
- [x] bump version
- [ ] release 1.1.1 to CHaP

**Comment by angerman** [comment]
Sigh, so this is green, except for a busted cicero call.

**Review by Soupstraw — APPROVED** [review]
LGTM

**Pull request merged**
