### PR TITLE
Bump up the cardano-ledger-api version

### PR DESCRIPTION
**Pull request by lehins**
# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Review by disassembler — APPROVED** [review]

**Comment by teodanciu** [comment]
This is for the Query, right?

**Comment by lehins** [comment]
> This is for the Query, right?

No, it was my fault, I forgot to bump up the version (in the cabal file) due to some breaking changes I introduced in #3508

**Comment by teodanciu** [comment]
> > This is for the Query, right?
> 
> No, it was my fault, I forgot to bump up the version (in the cabal file) due to some breaking changes I introduced in #3508

Ah I see, thanks

**Review by teodanciu — APPROVED** [review]
Looks good to me

**Pull request merged**
