### PR TITLE
Fix wrong prose for new epoch environment

### PR DESCRIPTION
**Pull request by WhatisRT**
# Description

The environment for NEWEPOCH is empty, but the prose claimed otherwise. Found in #4043.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Comment by zuzunker** [comment]
Does this also remove the mention that pools should be removed at the end of their retirement epoch?

**Review by lehins — APPROVED** [review]
Thank you.

**Comment by zuzunker** [comment]
> Does this also remove the mention that pools should be removed at the end of their retirement epoch?

@WhatisRT ?

**Comment by WhatisRT** [comment]
Ah, sorry, I missed that from the original discussion. Fixed in #4093.

**Pull request merged**
