### PR TITLE
Add a hidden skiplist file for `git fsck` and a note about using it

### LINKED ISSUE #4749: Remove usage of git submodule for `cardano-mainnet-mirror`
Reported by @michalrus:
```
❯ git clone  --recurse-submodules=never https://github.com/IntersectMBO/cardano-ledger.git
Cloning into 'cardano-ledger'...
remote: Enumerating objects: 179162, done.
remote: Counting objects: 100% (1276/1276), done.
remote: Compressing objects: 100% (514/514), done.
remote: Total 179162 (delta 998), reused 854 (delta 676), pack-reused 177886 (from 1)
Receiving objects: 100% (179162/179162), 113.63 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (101207/101207), done.
error: object eb6fb9bef41871323404b2c19e23fb5550ef04c9: gitmodulesUrl: disallowed submodule url: https://github.com/:input-output-hk/cardano-mainnet-mirror.git
fatal: fsck error in pack objects
fatal: index-pack failed
```

> The submodule URL has a colon where it should have a slash: https://github.com/:… instead of https://github.com/….

We do not use `cardano-mainnet-mirror` aside from some byron era tests. We retrieve that repo differently on CI, so we do not need it as a git submodule. It should be removed.

### PR DESCRIPTION
**Pull request by neilmayhew**
# Description

Closes #4749

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Review by Lucsanszky — APPROVED** [review]
LGTM, I don't think there is a better way. Just like in the case of the `git blame` config and ignoring certain revisions, we just have to accept the slight inconvenience of running those commands manually. 
One minor thing: I might rather add this to `CONTRIBUTING.md` but don't really have a strong opinion on the matter, I'll leave it up to you.

**Review by lehins — APPROVED** [review]
I do agree with @Lucsanszky that `CONTRIBUTING.md` is a more natural place for it. But, we can move it there at any point later whenever we'll be doing other work related to documentation.
As long as this is recorded somewhere it is already a very nice improvement.
Thank you @neilmayhew !

**Comment by neilmayhew** [comment]
Thanks, both.

The reason I put it in README rather than CONTRIBUTING is that people are more likely to see it there before cloning. I think it's unlikely they'll read CONTRIBUTING before cloning. However, we could shrink the note in README to a reference to the relevant section in CONTRIBUTING, such as "If you get an error from git when cloning, see ...".

Even so, let's leave it this way for now.

**Comment by michalrus** [comment]
Thank you! 🙇

**Pull request merged**
