### PR TITLE
Update cardano-ledger-alonzo to the new Plutus bytestrings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by michaelpj** [comment]
Looks like a real error.

**Comment by JaredCorduan** [comment]
> Looks like a real error.

Did this PR intend on bumping the version of Plutus? I'm seeing:

```
src/Cardano/Ledger/Alonzo/Data.hs:102:37: error:
    Not in scope: type constructor or class ‘Plutus.BuiltinByteString’
    Module ‘Plutus.V1.Ledger.Api’ does not export ‘BuiltinByteString’.
    |
102 | deriving anyclass instance NoThunks Plutus.BuiltinByteString
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by michaelpj** [comment]
Ah yes, we are trying to keep `plutus-staging` compiling, that way the eventual merge back to master is easy. So @ak3n you probably do want to include a bump of the `plutus` pin to point to your branch.

**Comment by ghost** [comment]
Oops, yep, updated! (oh, it means I can't rebase the PR anymore)

**Comment by michaelpj** [comment]
Yeah, it's a tricky little dance :/

**Comment by michaelpj** [comment]
Or you can rebase, but then you need to force push this branch too :upside_down_face:

**Review by JaredCorduan — APPROVED** [review]
:+1:

**Comment by ghost** [comment]
Oh, one of the tests has failed. Is it critical?

**Comment by michaelpj** [comment]
It's one of the quickcheck tests that sometimes fails due to discards, I restarted them, let's see.

**Comment by ghost** [comment]
Nice, thanks! I think we can merge it.

**Comment by JaredCorduan** [comment]
> It's one of the quickcheck tests that sometimes fails due to discards, I restarted them, let's see.

yea, the discard problem has gotten much worse recently, I apologize.

**Pull request merged**
