### PR TITLE
Add versioned CBOR instances for crypto primitives

### PR DESCRIPTION
**Pull request by lehins**
This PR moves all ToCBOR and FromCBOR instances from `cardano-crypto-class` and `cardano-crypto-praos` packages. Actual decoders are still defined in `cardano-crypto-class`

 Instances for `PraosVRF` in this PR depends on  https://github.com/input-output-hk/cardano-base/pull/316

### CODE REVIEW

**Review by JaredCorduan — APPROVED** [review]
LGTM!

**Comment by JaredCorduan** [comment]
@lehins - I forgot about the changelog, we should add all this goodness to it.

**Comment by lehins** [comment]
> I forgot about the changelog

I didn't, there is already an entry in changelog:

* Start on the `cardano-ledger-binary` package as a replacement for `cardano-binary` package: #3036

I'll add more PR numbers to that entry once the work is complete

**Comment by lehins** [comment]
:smile: I did however made a mistake on the PR number. I'll fix that

**Pull request merged**
