### PR TITLE
Removed `Shaped` instance for `Rep`

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
# Description

 and replace its uses with `TypeRep` based instances

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
It would be good to get the input of @lehins and @TimSheard on this one

**Review by lehins — APPROVED** [review]
Another amazing simplification. Perfect!!

Would be nice to @TimSheard review on this as well, however.

**Comment by MaximilianAlgehed** [comment]
@lehins there appear to be some flaky tests. Should we log these somewhere to make sure someone can go back and fix them at some point?

**Comment by lehins** [comment]
> Should we log these somewhere to make sure someone can go back and fix them at some point?

No point. Everyone knows about it, so it is just a matter of time and priority till we get to it.

**Pull request merged**
