### PR TITLE
Bump version of cardano-ledger-byron

### PR DESCRIPTION
**Pull request by erikd**
@lehins Was in the process of fixing this and got the sequence of operations wrong.

### CODE REVIEW

**Comment by JaredCorduan** [comment]
The CI failure looks unrelated to this PI, and is documented in #3460, so I will re-run CI.

**Comment by JaredCorduan** [comment]
@erikd I don't see anything in the changlog for 1.0.0.1: https://github.com/input-output-hk/cardano-ledger/blob/6ae2dc37b576a18afa288ea5df38e9a7440bccee/eras/byron/ledger/impl/CHANGELOG.md

**Comment by erikd** [comment]
I was not asked to update the change log, just to bump the version.

Anyway, added a entry to the changelog.

**Comment by erikd** [comment]
CI failure unrelated to my change.

**Review by JaredCorduan — APPROVED** [review]

**Pull request merged**
