### PR TITLE
cardano-ledger (as used in cardano-node@master and 1.34.5) with 9.2 compatibility

### PR DESCRIPTION
**Pull request by newhoggy**
This PR builds the foundation for a cardano-node@master and cardano-node@1.34.5 with 9.2 support. Both reference cardano-ledger@f49879. We therefore want to create a cardano-ledger@f49879 + 9.2 compatibility release, so that cardano-node@master, and cardano-node@1.34.5 can be made 9.2 compatible, until ledger@master, which is since #3041 9.2 compatible is integrated into cardano-node@master.

cardano-node@master references f49879a79098d9372d63baa13b94a941a56eda34 but should really reference c7c63dabdb215ebdaed8b63274965966f2bf408f (tag: ledger/1.0.0)
while ouroborus-network@master references 49613f11e034485c8377945c86c0465726c0860c (tag: ledger/1.1.0)

```
c7c63dabd (tag: node/1.35.3, tag: ledger/1.0.0) Merge pull request #2938 from input-output-hk/jc/fix-alonzo-minfee-on-release-1-0-0
7bec14d52 the alonzo UTxO rule to use alonzo minfee function
ebcf1a893 Merge pull request #2917 from input-output-hk/jc/update-plutus-on-release-1-0-0
e54e85a18 update plutus
f49879a79 Merge pull request #2909 from input-output-hk/jj/nothunks
```
(node@master -- while referencing f49879a79, should reference c7c63dabd for coherence).

```
7f7a8ae75 Merge pull request #2960 from input-output-hk/jc/set-utf8-in-nix-shell
49613f11e (tag: ledger/1.1.0) Merge pull request #2981 from input-output-hk/lehins/revert-renaming-of-environment
c98ea168c Update Changelog with new renamings
4c8306206 Rename back the Environment types:
b24fa846e Merge pull request #2979 from input-output-hk/lehins/fix-performance-issues-due-to-inlining
a46d52bc2 Merge pull request #2978 from input-output-hk/lehins/minimize-constraints-to-avoid-ghc-bug
af68c1cd9 Add a whole bunch of `INLINE` and `SPECIALIZE` pragmas
651d325c4 Keep number of constraints to the minimum in order to work around a ghc bug:
2eafa6e55 Merge pull request #2972 from input-output-hk/td/unify-rules-types-across-eras
67b322fc1 Prefix rule-types with era name in babbage
835fe353d Prefix rule-types with era name in alonzo
651af86d6 Prefix rule-types with era name in shelley-ma
cf7d2c77c Prefix rule-types with era name in shelley
b44a3b895 Merge pull request #2967 from input-output-hk/ts-conway-consenus-test
a07bc36cd Added Consenus tests for Conway era.  Also extended Test.Cardano.Ledger.Generic.Proof and related modules to the Conway era. Added Conway unit tests (TwoPhase
Validation BabbageFeatures) Added Conway property tests
67bce2c27 Add two invalid Babbage feature tests: ReferenceInputsNotSupported and ReferenceScriptsNotSupported (#2971)
93eda91f5 Added precision to the Babbage era specification concerning the use of new features with PlutusV1 scripts (#2970)
52125a3fb Merge pull request #2966 from input-output-hk/jj/conway-json
96a5618d0 Ormolize
1a1e7dfcd Implemented FromJSON manually
1d3331748 Added FromJSON instance to ConwayGenesis
d4743d896 Merge pull request #2963 from input-output-hk/jj/conway-genesis
66cb66463 Merge pull request #2959 from input-output-hk/jc/move-alonzo-spec-out-of-draft
5302e70dc Update GenDelegs in the DState
31803c8df Added ConwayGenesis as the translation context
d696f1d47 Merge pull request #2950 from input-output-hk/lehins/fixups-to-recent-restructure
275f90cfc Merge pull request #2962 from input-output-hk/td/remove-redundant-dependency
ec7dd5651 Remove unused data-default-class library from shelley-ma dependencies
01a43bebd Avoid ghc bug that causes an infinite loop
0f5307fee makefile for alonzo spec
7f7a8ae75 Merge pull request #2960 from input-output-hk/jc/set-utf8-in-nix-shell
f8e6f561c set LC_ALL="C.UTF-8" inside nix shell
dd5109edf mark alonzo spec as pubic (not draft)
83c9627bc Merge pull request #2956 from LudvikGalois/ludvikgalois/title-case-follow-the-satoshi
be3a19c29 Merge pull request #2957 from input-output-hk/newhoggy/new-calculatePoolDistr'-function
f436bff8f New calculatePoolDistr' function which is the same as calculatePoolDistr, but additionally takes a filter function to constrain returned results
fdfeca9e2 Fix typo in changelog of delegation design spec
74dc096a1 Change "Follow the Satoshi" to title case
892eed66a Merge pull request #2955 from LudvikGalois/ludvikgalois/unboxed-vector-maps
3bf6a4b7e Merge pull request #2953 from input-output-hk/ts-validate-by-phase-onTopOf-alexisPr
f841c0cd1 Merge pull request #2924 from input-output-hk/ts-testPropertyNamed
8a3f91687 Merge pull request #2762 from SebastienGllmt/patch-5
1f1e0f6a0 Moved Language.hs to core. Added Phase types, and changed the classes EraScript and EraTx methods to use phased types. This means validate methods only work on scripts valid for a given phase, and this is enforced by types.
ad42466fc Replaced testProperty with our own version written in terms of testPropertyNamed
3392ae6ac Make VMap.VU an Unboxed Vector
11e4d4a8a Merge pull request #2942 from input-output-hk/jc/clarify-PVCannotFollowPPUP-comment
49c687faf Add Byron CDDL to README
25c19a08f better comment for the PVCannotFollowPPUP failure
93b5d5421 Merge pull request #2945 from input-output-hk/lehins/new-conway-era
b8a3ea89d Add `FromSharedCBOR` constraint to the `EraTxOut`
fba18d078 Fix the changelog and add an entry for ConwayEra
c3a46e042 Introduce barebones for the new Conway Era
d10846cec Reduce duplication by creating a helper function `initialStateFromGenesis`
b56be4778 Create helper lens functions for defining EraTxOut and EraTxBody instances in future eras
c7c63dabd (tag: node/1.35.3, tag: ledger/1.0.0) Merge pull request #2938 from input-output-hk/jc/fix-alonzo-minfee-on-release-1-0-0
```

https://github.com/input-output-hk/cardano-ledger/compare/c7c63dabdb215ebdaed8b63274965966f2bf408f...49613f11e034485c8377945c86c0465726c0860c does not look like we could (or should) trivially assume we can work from what's referenced in network. (It also bumps plutus).

we therefore should create a 9.2 compatible release based off of tag 1.0.0 (c7c63dabdb215ebdaed8b63274965966f2bf408f), which is what this PR tries to achieve.

---
depends on https://github.com/input-output-hk/plutus/pull/4945

### CODE REVIEW

**Comment by angerman** [comment]
@JaredCorduan can we get a proper release/0.1.0.0 branch (that's he version number I assume?) from `f49879a79`? It's effectively what we _use_ today in [cardano-node@master](https://github.com/input-output-hk/cardano-node/blob/e0d6b168361f24dbee93d0cfbad3bc2f9c39065e/cabal.project#L150-L151), but [CHaP references c7c63dabdb215ebdaed8b63274965966f2bf408f for 0.1.0.0](https://github.com/input-output-hk/cardano-haskell-packages/blob/main/_sources/cardano-ledger-core/0.1.0.0/meta.toml).

**Comment by angerman** [comment]
Ahh, ok. So here we are now:
```
c7c63dabd (tag: node/1.35.3, tag: ledger/1.0.0) Merge pull request #2938 from input-output-hk/jc/fix-alonzo-minfee-on-release-1-0-0
7bec14d52 the alonzo UTxO rule to use alonzo minfee function
ebcf1a893 Merge pull request #2917 from input-output-hk/jc/update-plutus-on-release-1-0-0
e54e85a18 update plutus
f49879a79 Merge pull request #2909 from input-output-hk/jj/nothunks
```

**Comment by angerman** [comment]
@newhoggy this looks pretty much like https://github.com/input-output-hk/cardano-ledger/compare/release/1.0.x...release/1.0.x-ghc-9.2.4, (#3081), so you might have doe this before already :-) We just need to resurrect the PR!

**Comment by JaredCorduan** [comment]
@newhoggy @angerman - is this draft PR still needed, or can we close it?

**Comment by JaredCorduan** [comment]
This PR appears to be stale, I'm going to close it for now, but please feel free to re-open it if it is still relevant.

**Pull request closed without merging**
