### PR TITLE
Merge plutus-staging

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by michaelpj** [comment]
Compile error doesn't seem to be my fault, something wrong with the preprocessor?

**Comment by michaelpj** [comment]
Tut tut Jared, editing a generated file :) https://github.com/input-output-hk/cardano-ledger-specs/commit/2e9f03e68442ea4c787c73d75fcd8a2c9d13cf4d#diff-42b9462e24b5d52345a25696d32bfa8c593ce95b5c2c9c342680b06dfd58bc51

I'll hack something into the preprocessor.

**Comment by JaredCorduan** [comment]
> Tut tut Jared, editing a generated file :) [2e9f03e#diff-42b9462e24b5d52345a25696d32bfa8c593ce95b5c2c9c342680b06dfd58bc51](https://github.com/input-output-hk/cardano-ledger-specs/commit/2e9f03e68442ea4c787c73d75fcd8a2c9d13cf4d#diff-42b9462e24b5d52345a25696d32bfa8c593ce95b5c2c9c342680b06dfd58bc51)
> 
> I'll hack something into the preprocessor.

:face-palm: I should have noticed that comment three lines up, sorry. Perhaps that is a weird place to put the `defaultCostModel`.

**Review by JaredCorduan — APPROVED** [review]
:+1:

**Comment by michaelpj** [comment]
I hacked something in, I'll leave it to you to find a nicer way!

**Comment by JaredCorduan** [comment]
> I hacked something in, I'll leave it to you to find a nicer way!

perfect, thank you!

**Pull request merged**
