### PR TITLE
update cardano-base

### PR DESCRIPTION
**Pull request by JaredCorduan**
This bring in:
 * https://github.com/input-output-hk/cardano-base/pull/240

### CODE REVIEW

**Review by lehins — APPROVED** [review]

**Comment by nc6** [comment]
The golden files are changed here. Do we expect this?

**Comment by JaredCorduan** [comment]
> The golden files are changed here. Do we expect this?

definitely not, they should not have changed. I do not understand why removing those rewrite rules would change the representation...

**Comment by lehins** [comment]
I know exactly why these test fail!

How many bytes is this as hex: `"01020304"` ... 4 bytes, but our hashes are expected to be 8 bytes. So tests where always buggy

**Comment by lehins** [comment]
Instead of `UnsafeHash` we should use `hashFromBytes`, this way at least we'll get a proper failure when hashing algorithm changes in tests. In other words `UnsafeHash` should never be used and IMHO it shouldn't even be exported.

**Comment by JaredCorduan** [comment]
> Instead of `UnsafeHash` we should use `hashFromBytes`, this way at least we'll get a proper failure when hashing algorithm changes in tests. In other words `UnsafeHash` should never be used and IMHO it shouldn't even be exported.

So a previous PR changed the hashing algorithm, and the use of `UnsafeHash` prevented the golden tests from noticing this?

**Comment by JaredCorduan** [comment]
thanks for cleaning this up @lehins , looks good to me!

**Pull request merged**
