### PR TITLE
Add a CI status check to prevent merging PRs that contain merges

### LINKED ISSUE #4307: Add a CI status check to prevent merging PRs that already have merges in them
GH has a button to bring a PR branch up to date with `master` and by default it merges `master` into the PR branch. This causes messy, hard-to-follow history in the repo, and it's not obvious from the UI what GH has done in response to clicking the button.

We will create an additional status check that will prevent merging, as a separate job within the `haskell.yml` workflow, similar to the code-formatting checks. It will check that the branch contains no merges (ie no commits with more than one parent) between `master` and the tip of the PR branch. It won't affect `master` itself because there won't be any commits to check.

If someone needs to bring in commits from another PR or feature branch, they will need to rebase their branch onto the other rather than merging the other into their branch.

The check logic will be:

```shell
! git log --merges --format=%H master..HEAD | grep -q .
```

### PR DESCRIPTION
**Pull request by neilmayhew**
Closes #4307

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Review by lehins — APPROVED** [review]
Awesome! Thank you!

**Review by lehins — CHANGES_REQUESTED** [review]
Looks like this git command does not work as expected: https://github.com/IntersectMBO/cardano-ledger/actions/runs/8886398544/job/24399775489?pr=4308

**Comment by neilmayhew** [comment]
This seems to be working now. It failed (for the right reasons!) on the last run when there was still a merge commit on the branch. If it passes this time, it should be good to go.

**Review by lehins — APPROVED** [review]
Perfect!

**Pull request merged**
