### PR TITLE
Parameterize the type of epochInfoWithError

### PR DESCRIPTION
**Pull request by nfrisby**
The fundamental change is here: https://github.com/input-output-hk/cardano-ledger-specs/pull/2344/files#diff-3e75c353cc8150583a6fe776b1b9b0ec87aefbd08207698ad659da8dd11445f4R325

### CODE REVIEW

**Comment by nfrisby** [comment]
@JaredCorduan @nc6 Does this change seem controversial at all to you?

I opened this PR as a Draft because I'm not certain we need it (nevermind that I'd be surprised if it typechecks as-is). But I anticipate we want it. Thanks for your thoughts.

**Comment by JaredCorduan** [comment]
This is totally fine by me, but @nc6 may be aware of issues I don't know about

**Comment by nc6** [comment]
Can somebody explain the motivation for this change? The change itself seems fine, but I'm not seeing why it's useful.

**Comment by DavidEichmann** [comment]
@nc6 The motivation is that I'm trying to add a node-to-client query for the ledger configuration. In some cases, the ledger config contains an `EpochInfo` which is just a dummy value. This PR hopes to clean that up a bit and allow us to use e.g. `()` instead of `EpochInfo` so that we can avoid using a dummy value.

Another related change is: https://github.com/input-output-hk/cardano-base/pull/220 (details in the PR description)

**Comment by nfrisby** [comment]
@DavidEichmann and I had a call. We're now trying an alternate path that does not need this PR. So we'll likely close it, if that path works out.

I do think we will eventually want this, but during our call we realized that this is only one step towards a our ultimate objective and it wouldn't provide much until we figure out the rest of the steps. So it should wait until that happens (if ever :/).

**Comment by nc6** [comment]
Closing this until such time as we decide it's needed. I'll leave the branch undeleted for now.

**Pull request closed without merging**
