### PR TITLE
cabal.project: Bump index states

### PR DESCRIPTION
**Pull request by erikd**
This is the first step in making this build with `ghc-9.8`. Only the `index-state` values were changed.

### CODE REVIEW

**Comment by lehins** [comment]
Whenever index state is updated we also need to update nix flakes

**Comment by erikd** [comment]
@lehins Updating the CHaP index-state was easy:
```
nix flake lock --update-input CHaP
```
However, I tried every combination I could think of for
```
nix flake lock --update-input hackage.nix
```
and none of them worked.

**Comment by michaelpj** [comment]
@erikd it's written down: https://github.com/input-output-hk/cardano-ledger/blob/master/CONTRIBUTING.md?plain=1#L64

**Comment by erikd** [comment]
> @erikd it's written down: https://github.com/input-output-hk/cardano-ledger/blob/master/CONTRIBUTING.md?plain=1#L64

So why is it different between projects? I have touched 10 different input-output-hk projects in the last week. Every project doing it in a unique snowflake way is a HUGE pain in the neck.

**Review by lehins — APPROVED** [review]
:+1:

**Pull request merged**
