### PR TITLE
added reward cycle example image to shelley spec

### PR DESCRIPTION
**Pull request by JaredCorduan**
I've added this image:

reward-cycle

with an accompanying explanation to the Shelley formal spec. Feedback is welcome!

### CODE REVIEW

**Comment by polinavino** [comment]
Impressive LaTeX drawings! 

I think the looping light green arrow is a bit confusing, I would maybe draw it to the end of e2, with a caption on the arrow something like "parameters not yet in effect (Alice's opportunity to redelegate)"

**Comment by polinavino** [comment]
Also, the green square on blue arrow (and light green on light blue) isn't easy to figure out without reading the text, as it seems like a specific e4 block is used in the stake calculation, rather than all the data about block production gathered in e3. 

Maybe use a triangle or a circle, to distinguish, instead?

**Comment by JaredCorduan** [comment]
> Impressive LaTeX drawings!
> 
> I think the looping light green arrow is a bit confusing, I would maybe draw it to the end of e2, with a caption on the arrow something like "parameters not yet in effect (Alice's opportunity to redelegate)"

Thanks!

The source of truth for the current (un-snapshotted) pool parameters, the `poolParams` map in `PState`, is updated with the cached change on the epoch boundary (right after the snapshot is taken), which is what that loopy arrow is trying to show.

**Comment by JaredCorduan** [comment]
> Also, the green square on blue arrow (and light green on light blue) isn't easy to figure out without reading the text, as it seems like a specific e4 block is used in the stake calculation, rather than all the data about block production gathered in e3.
> 
> Maybe use a triangle or a circle, to distinguish, instead?

yea, I agree, it's not clear. Maybe a darker green `Bob`? :thinking:

**Comment by JaredCorduan** [comment]
I removed the potentially confusing green squares on the snapshots, and replaced it with "4 blocks" on the darker blue line.

**Review by polinavino — APPROVED** [review]
:+1::heavy_check_mark:

**Pull request merged**
