### PR TITLE
move alonzo spec out of draft

### LINKED ISSUE #2958: Alonzo spec linked in README is marked "draft".
Is this accurate or up to date? If so, where can I find more information about this?

### PR DESCRIPTION
**Pull request by JaredCorduan**
This PR:

* moves the Alonzo spec out of draft and into public
* fixes `IOHKCoverPage.sty`
* adds a makefile for the Alonzo spec

resolves #2958

### CODE REVIEW

**Comment by teodanciu** [comment]
Just curious, who or what will run the Makefile?

**Comment by JaredCorduan** [comment]
> Just curious, who or what will run the Makefile?

good question. by the looks of it, I might be the only person who enjoys using them :laughing:

**Review by teodanciu — APPROVED** [review]
Looks good to my latex-unknowing eye.  However I ran "make watch" and saw the change in the pdf as expected. 

Wondering what's happening with [the link in Readme](https://hydra.iohk.io/job/Cardano/cardano-ledger/specs.alonzo-ledger/latest/download-by-type/doc-pdf/alonzo-changes)? Will it be automatically updated to point to the version that is not a draft?

**Comment by JaredCorduan** [comment]
> Wondering what's happening with [the link in Readme](https://hydra.iohk.io/job/Cardano/cardano-ledger/specs.alonzo-ledger/latest/download-by-type/doc-pdf/alonzo-changes)? Will it be automatically updated to point to the version that is not a draft?

yep, that link always points to the latest CI build of master (draft or not).

**Pull request merged**
