### PR TITLE
Update CHaP, remove constraints from cabal file

### PR DESCRIPTION
**Pull request by michaelpj**
I revised a bunch of stuff in CHaP, the constraints are no longer needed.

### CODE REVIEW

**Comment by lehins** [comment]
@michaelpj Thanks. Could you run `./scripts/cabal-format.sh` and we'll merge it?

**Comment by michaelpj** [comment]
Done. If only it was a pre-commit hook so I couldn't forget :trollface:

**Review by lehins — APPROVED** [review]
Thank you!

**Comment by lehins** [comment]
> If only it was a pre-commit hook so I couldn't forget

It was part of the checklist in the PR that you deleted :stuck_out_tongue_closed_eyes:

**Pull request merged**
