### PR TITLE
Simplify the implementations of `hasOrd` and `hasEq`

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
# Description

This simplifies the implementation by relying on a generalization of the `IsTypeable` dict

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@TimSheard another nice trick!

**Comment by MaximilianAlgehed** [comment]
@lehins there is a bug in fourmolu - it's suggested change does not have the same meaning as the original code and fourmolu knows this. However, the CI still fails.

**Comment by lehins** [comment]
> there is a bug in fourmolu

@MaximilianAlgehed Can you report it as a bug?

It can either be a bug in ormolu or fourmolu, so you'd need to try applying a snippet using latest versions of both of those tools and report it on the appropriate repo, I suspect it will be [`ormolu`](https://github.com/tweag/ormolu), since that's the package responsible for getting the source AST and majority of the formatting decisions.

Should be as simple as downloading the ormolu binary from the repo release and applying it to the snippet that has the semantic broken by it.

**Comment by MaximilianAlgehed** [comment]
This is the specific error that I got on commit `897a6dd`:
```
@@ -443,6 +443,6 @@
    MaybeR (repHasInstances -> ia) -> requireInstances ia
    GenR (repHasInstances -> IsTypeable) -> IsTypeable

- lubIs :: ((c a, c b) => c (f a b)) => Is c a -> Is c b -> Is c (f a b)
+ lubIs :: (c a, c b) => c (f a b) => Is c a -> Is c b -> Is c (f a b)
  lubIs Is Is = Is
  lubIs _ _ = Isn't
@@ -458,6 +458,6 @@
  lubInstances (Type eq_a ord_a) (Type eq_b ord_b) =
    Type (lubIs eq_a eq_b) (lubIs ord_a ord_b)

- requireIs :: (c a => c (f a)) => Is c a -> Is c (f a)
+ requireIs :: c a => c (f a) => Is c a -> Is c (f a)
  requireIs Is = Is
  requireIs _ = Isn't

  AST of input and AST of formatted code differ.
    at libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/TypeRep.hs:446:11-33
    at libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/TypeRep.hs:446:39-[7](https://github.com/input-output-hk/cardano-ledger/actions/runs/6236465538/job/16927825935#step:4:8)0
    at libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/TypeRep.hs:461:15-2[8](https://github.com/input-output-hk/cardano-ledger/actions/runs/6236465538/job/16927825935#step:4:9)
    at libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/TypeRep.hs:461:34-53
  Please, consider reporting the bug.
  To format anyway, use --unsafe.
```

**Comment by MaximilianAlgehed** [comment]
I checked the issue tracker over at the fourmolu repo and a very similar issue has been marked as resolved https://github.com/fourmolu/fourmolu/pull/340. Before I go digging around with this - are we sure we are using the latest version of fourmolu in this repo or are we on a version from before this fix?

**Comment by lehins** [comment]
> are we sure we are using the latest version of fourmolu

Good point. We are not. I'll submit a PR in a moment that updates it. So, you might be able to remove this commit https://github.com/input-output-hk/cardano-ledger/pull/3735/commits/d2daee739c59be077fd454ae27fe2fd81ef671ef

**Comment by lehins** [comment]
> Good point. We are not. I'll submit a PR in a moment that updates it. So, you might be able to remove this commit https://github.com/input-output-hk/cardano-ledger/commit/d2daee739c59be077fd454ae27fe2fd81ef671ef

@MaximilianAlgehed Just in case you didn't notice #3742 fixed the issue with outdated version of fourmolu

**Review by lehins — APPROVED** [review]
This is way too cool! I love it :heart:

**Comment by MaximilianAlgehed** [comment]
@lehins that updated version of fourmolu doesn't appear to have fixed the issue. Perhaps the fix hasn't been released yet? I can put back the work-around for now with a note to follow this up in the future.

**Comment by lehins** [comment]
>  I can put back the work-around for now with a note to follow this up in the future.

Before putting workarounds, I'd suggest verifying the problem is not fix and submitting an issue with a reproducer case on fourmolu or ourmolu repo, depending who's responsible for the problem

**Comment by MaximilianAlgehed** [comment]
@lehins https://github.com/fourmolu/fourmolu/issues/374

**Comment by lehins** [comment]
@MaximilianAlgehed could you rebase this on master? We've had a PR merged.

FYI, now that you have write permissions to the repo, if you create branches on this repo, instead of a fork, I'd be able to do rebases for you right in the github UI, which would remove this inconvenient friction.

**Comment by MaximilianAlgehed** [comment]
Yes, I'll build my future PRs on this repos origin

**Pull request merged**
