### PR TITLE
[DOCS] ReadTheDocs

### PR DESCRIPTION
**Pull request by robcohen**
*   Merge docs.cardano.org cardano-ledger-specs site

### CODE REVIEW

**Comment by nc6** [comment]
Hey Rob. Can you add some more detail on what this PR is aiming to achieve, what its benefits are etc? In particular, I have a few questions so far:

- The changes to the README remove a lot of information. Is the intention that this should be read on RTD? If so, we need to make sure that's made clear and linked to. 
- How is the RTD site kept up to date with changes made here? Do we need to add a hook in somewhere? 

I'll leave doing a more thorough review of the contents of this PR until you've had a chance to update with some more of this context :-)

**Comment by robcohen** [comment]
> The changes to the README remove a lot of information. Is the intention that this should be read on RTD? If so, we need to make sure that's made clear and linked to.

The intention is that docs.cardano.org should be the go-to place for documentation on cardano.  
The documentation relevant to cardano-ledger-specs should be in the repo itself, and it should be the sole source that is used to build the cardano-ledger-specs section on RTD. If it helps, we can add links to the other markdown files that exist in /doc from the README

> How is the RTD site kept up to date with changes made here? Do we need to add a hook in somewhere?

No hook is needed, it will automatically update (Charles Morgan will take care of it). I can get your team access to see the generated logs if you would like in case you are trying to debug a RTD build.

**Comment by JaredCorduan** [comment]
> If it helps, we can add links to the other markdown files that exist in /doc from the README

that would be great! or even just a single link to the RTD and mention that there is more helpful stuff there

**Comment by robcohen** [comment]
My recommendation would be to do this in GitHub itself, in the URL field for the project . Would that work?

**Comment by JaredCorduan** [comment]
> My recommendation would be to do this in GitHub itself, in the URL field for the project . Would that work?

Would this mean not providing a link to RTD in the main readme? Is this because it would then seem weird on RTD having this self referential link?

**Comment by robcohen** [comment]
Yeah, it might look a little weird to link to itself. There are worse things we can do however, it's up the project devs / project owner how they want it to look. Whatever you want I'll put in.

**Comment by nc6** [comment]
The README file is the main place that people on github will see when they come to look at this project. So it must work as a self-contained document, not assuming that it will be viewed on RtD.

I think the best solution would be that the README itself should not be published on RtD. It should contain an overview, a link to the main documentation index (which should be created separately) in RtD and possibly direct links to the most common questions. Then most of the information can move to the `doc` directory and be updated there.

Perhaps as a first step could you add the RtD config and the additional pages without making README changes. Then we can review the information there and update the readme later.

**Comment by JaredCorduan** [comment]
> I think the best solution would be that the README itself should not be published on RtD. It should contain an overview, a link to the main documentation index (which should be created separately) in RtD and possibly direct links to the most common questions. Then most of the information can move to the `doc` directory and be updated there.

I agree!

**Comment by robcohen** [comment]
If we don't include it, then there will be multiple files that contain the same information. Much easier to just add links to the readme to point to the primary getting started documents and the docs url. "Please see INSTALLATION.md for installation instructions, etc" I would prefer the README only include an overview of the repo software and links to where the users can get more info.

**Comment by savicsava** [comment]
Hi all. Let me just clarify.
Devs should be creating documentation that tech writers will process and organize in a uniform way across multiple repos, merging all things in one source of truth on docs website.

So please let's be clear who does what - All content that is produced is with devs, the organization of the content in the best possible way is with the Docs team.

**Comment by JaredCorduan** [comment]
> If we don't include it, then there will be multiple files that contain the same information. Much easier to just add links to the readme to point to the primary getting started documents and the docs url. "Please see INSTALLATION.md for installation instructions, etc" I would prefer the README only include an overview of the repo software and links to where the users can get more info.

I think Nick's ideas is that we do _not_ duplicate any information, it's just that the main github readme can be the landing page for github (with links to the relevant shared information), pointing to all the common stuff in the `docs` directory. This way we do not have to make the main github readme try to exist in two worlds simultaneously.

```
github landing -> common stuff <- RtD landing
```

**Comment by JaredCorduan** [comment]
@robcohen can I close this until we have a plan for how to keep the Readme in github understandable in github?

**Comment by robcohen** [comment]
I am only assisting with docs occasionally, please ask @nahern

**Comment by robcohen** [comment]
I am only assisting with docs occasionally, please ask @nahern

**Comment by JaredCorduan** [comment]
replaced by #1960

**Pull request closed without merging**
