### PR TITLE
Initial RTD setup

### PR DESCRIPTION
**Pull request by michaelpj**
This is another attempt at getting RTD setup here. Compared to https://github.com/input-output-hk/cardano-ledger-specs/pull/1801/files:
- It does not hijack the README: I agree that that's for people looking at the repository and we should confuse it with content for the doc site.
- It does not attempt to provide any content: I'm hoping that we will rapidly get some from what Polina and Fernando have been writing, and I want to contribute some myself.

I haven't set it up on RTD itself yet, but I will do that if people are on board.

You can build the site with nix, and also from inside a `nix-shell` by using `sphinx-build` directly.

### CODE REVIEW

**Comment by nc6** [comment]
Thanks for this, looks great!

**Review by nc6 — APPROVED** [review]

**Comment by michaelpj** [comment]
Ah, I guess buildkite isn't going to build this unless I make a PR from this repository? Someone probably needs to give me write access so I can push a branch here, then.

**Comment by JaredCorduan** [comment]
> Ah, I guess buildkite isn't going to build this unless I make a PR from this repository? Someone probably needs to give me write access so I can push a branch here, then.

You should already have write access @michaelpj . I'm happy to cherry pick the PR in a new branch in the main repo if you'd like, though. Thanks again!

**Comment by michaelpj** [comment]
So I do: https://github.com/input-output-hk/cardano-ledger-specs/pull/1960

**Pull request closed without merging**
