### PR TITLE
Bump plutus and fix breaking changes

### PR DESCRIPTION
**Pull request by kk-hainq**
Mainly updating `ByteString` to `BuiltinByteString`.

Reference:
- https://github.com/input-output-hk/plutus/commit/1e287eb7eefb25b4a41f4d930ae0f8335431304f

### CODE REVIEW

**Comment by JaredCorduan** [comment]
thank you for helping out @kk-hainq ! We actually already moved to `BuiltinByteString` (see #2407).

**Comment by kk-hainq** [comment]
> thank you for helping out @kk-hainq ! We actually already moved to `BuiltinByteString` (see #2407).

Oh, it's in `plutus-staging`! Maybe I can force push the delete of the duplicate entry in `cabal.project` for this one?

**Comment by kk-hainq** [comment]
> thank you for helping out @kk-hainq ! We actually already moved to `BuiltinByteString` (see #2407).

Oh, it's in `plutus-staging`! I think we can close this then, any idea when we can merge that one?

Also wonder if we can still force push to keep this one, for deleting the duplicate `flat` entry in `cabal.project`.

**Comment by JaredCorduan** [comment]
> Oh, it's in `plutus-staging`! I think we can close this then, any idea when we can merge that one?
> 
> Also wonder if we can still force push to keep this one, for deleting the duplicate `flat` entry in `cabal.project`.

I'm not sure, @michaelpj probably knows more, though.

I can put up a separate PR to remove the `flat` entry. I'd have to do that anyway, since our CI won't run on forks. (which is really unfortunate, see https://github.com/buildkite/feedback/issues/293)

**Comment by kk-hainq** [comment]
> > Oh, it's in `plutus-staging`! I think we can close this then, any idea when we can merge that one?
> > Also wonder if we can still force push to keep this one, for deleting the duplicate `flat` entry in `cabal.project`.
> 
> I'm not sure, @michaelpj probably knows more, though.
> 
> I can put up a separate PR to remove the `flat` entry. I'd have to do that anyway, since our CI won't run on forks. (which is really unfortunate, see [buildkite/feedback#293](https://github.com/buildkite/feedback/issues/293))

Sure, thanks. I'll just close this for now then.

**Comment by michaelpj** [comment]
The workflow is to merge `plutus-staging` regularly, although we haven't worked out a schedule yet (we're still working on this process...). I was planning to do it today.

**Comment by kk-hainq** [comment]
> The workflow is to merge `plutus-staging` regularly, although we haven't worked out a schedule yet (we're still working on this process...). I was planning to do it today.

Cardano has brought us so much opportunity that we've been wanting to contribute a lot back. Bumping dependency versions of key components when there are breaking changes is a good start, please tell us if we could help in any way. 

We'd like to write more documentation, especially on Plutus and Smart Contracts too.

**Pull request closed without merging**
