### PR TITLE
Minor changes to shelley.cddl for ease of use

### PR DESCRIPTION
**Pull request by JaredCorduan**
replaces #1648 and #1649

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
I'm okay with this as long as Rob is okay 👍

**Review by dcoutts — APPROVED** [review]
lgtm

though probably easier to follow if the definition of each case follows the use in the sum type.

**Comment by JaredCorduan** [comment]
is this what you meant, @dcoutts ?

**Comment by rooooooooob** [comment]
I'm fine with this. I closed the other PR.

**Pull request merged**
