### PR TITLE
Bump Plutus to latest version.

### PR DESCRIPTION
**Pull request by nc6**
- Drop the (defunct) fee input field.
- Also fix some Haddock errors.

### CODE REVIEW

**Review by JaredCorduan — APPROVED** [review]
LGTM

**Comment by JaredCorduan** [comment]
this would close #2291, right @EncodePanda ?

**Comment by EncodePanda** [comment]
@JaredCorduan I think it does, yes. Let me close that ticket once I double-check this (I will upgrade dependencies on our end and see if everything works)

**Comment by EncodePanda** [comment]
Oh, wait. I thought it was merged already. I will wait till it's merged and then try to update consensus with bumped ledger and plutus.

**Comment by EncodePanda** [comment]
```
test/Test/Cardano/Ledger/Alonzo/Examples/Utxow.hs:81:1: error:
Error:     Could not load module ‘PlutusCore.Evaluation.Machine.ExBudgetingDefaults’
    It is a member of the hidden package ‘plutus-core-0.1.0.0’.
(....)
   |
81 | import qualified PlutusCore.Evaluation.Machine.ExBudgetingDefaults as P
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by nc6** [comment]
Darn, I had hoped that error only came on my machine. It's perplexing and I don't understand it. Will stare at it some more.

**Comment by EncodePanda** [comment]
🤞

**Comment by JaredCorduan** [comment]
thank you for figuring out what changed with the cost model @nc6 !

**Pull request merged**
