### PR TITLE
fix `prop_DELEG` in STS tests

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
# Description

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@lehins here is another flaky test - what does it mean when it fails with a test being "pending"

**Comment by lehins** [comment]
> here is another flaky test - what does it mean when it fails with a test being "pending"

Pending is not a failure. "pending" tests are the ones that have been disabled, because they are not essential and there is some work needed to get them to pass.

Failure CI is due to some byron test failure that I have not seen before:
```
1 out of 51 tests failed (98.82s)
Test suite byron-spec-ledger-test: FAIL
```

But, we don't need to worry about it, since byron code base is mostly read only.

**Comment by MaximilianAlgehed** [comment]
@lehins by earlier logic, shouldn't we turn the tests off as they would be in the way of auto-merge here? Slowing down merging on PRs.

**Comment by lehins** [comment]
> by earlier logic, shouldn't we turn the tests off as they would be in the way of auto-merge here? Slowing down merging on PRs.

The fact that I have never seen it before, means it is indeed an extremely rare failure and is not worth the time. That being said, please make sure to not introduce any new tests like that.

**Comment by MaximilianAlgehed** [comment]
@lehins same failure as here iirc:
https://github.com/IntersectMBO/cardano-ledger/pull/3730

**Comment by lehins** [comment]
> same failure as here iirc:

Please don't make me dig through the logs. Could you please paste the output of the test failure for the one from #3730 and this PR. This will tell us if it is indeed the same.

**Comment by MaximilianAlgehed** [comment]
Unfortunately the logs aren't saved from old CI runs.

> Looks like it, but it is the first time I see this failure, but this is from byron codebase and this is not something we are going to fix. So, no need to worry about it

Anyway, I'm just making sure I understand the standards of this code base and how you want things done.

**Review by lehins — APPROVED** [review]
:+1:

**Pull request merged**
