### PR TITLE
Adding native tokens documentation content

### PR DESCRIPTION
**Pull request by polinavino**
Porting existing google docs content about native tokens/multiasset ledger to the RTD in this repo

### CODE REVIEW

**Comment by polinavino** [comment]
The FAQ and Glossary sections are ready for review. The others are WIP

**Comment by michaelpj** [comment]
Which one am I reviewing? The MD version or the RST version? I think either will work, but can we pick one, please?

**Comment by michaelpj** [comment]
*poke*

**Comment by michaelpj** [comment]
I didn't re-review the content (don't have time), and I assume it's the same, but I checked over the rendering and it looks fine.

I think this could do with re-structuring to have topic-based explanations rather than putting everything under the FAQ, but we can do that later and it's not worth holding this up over that.

**Review by michaelpj — APPROVED** [review]

**Pull request merged**
