### PR TITLE
Add fast implementation of quicksort that does smart pivot choosing

### PR DESCRIPTION
**Pull request by lehins**
@TimSheard Here is a fast in-place unstable sort for SmallArray that I promised.

### CODE REVIEW

**Review by JaredCorduan — APPROVED** [review]
LGTM

**Comment by nc6** [comment]
@lehins Do we expect to need this in the end? If so, please merge, otherwise let's just close this PR. Can always resurrect it later.

**Comment by lehins** [comment]
@TimSheard Do you still need this sorting functionality?

**Comment by JaredCorduan** [comment]
I talked to @TimSheard , he said that unfortunately he no longer needs it.

**Pull request closed without merging**
