### PR TITLE
Organize locations for Haskell packages 

### PR DESCRIPTION
**Pull request by lehins**
Current story in consistent naming and placing is pretty sad. This PR will trying to fix all of it, except `byron`, I specifically left it out. Most of these changes will have to percolate to other repos that depends on `cardano-ledger-spec`, but that will be a pretty straightforward update that I could do in PRs for respective repositories. 

Please, let me know if any naming convention choices I made are not aligned with one's preference and we can adopt them instead. Most important here is consistency.

So far this PR takes care of the first two steps:

## Haskell modules

Shelley module names are inconsistent with the rest of the repo. This PR introduces renames in a backwards compatible manner with deprecation warnings:

* [x] `Shelley.Spec.NonIntegral` -> `Cardano.Ledger.NonIntegral`
* [x] `Shelley.Spec.Ledger` -> `Cardano.Ledger.Shelley`
* [x] `*.STS` -> `*.Rules`
* [x] `Test.Shelley.Spec.Ledger` -> `Test.Cardano.Ledger.Shelley`

## Haskell packages

* [x] - Package locations and required changes to `cabal.project` and other files found in the repo. Currently era specific implementation is located in inconsistently named paths. This PR moves them around to have a consistent pattern `eras/<era>/impl` and `eras/<era>/test-suite`
    * `shelley/chain-and-ledger/executable-spec` -> `eras/shelley/impl`
    * `shelley/chain-and-ledger/shelley-spec-ledger-test` -> `eras/shelley/test-suite`
    * `shelley-ma/impl` -> `eras/shelley-ma/impl`
    * `shelley-ma/shelley-ma-test` -> `eras/shelley-ma/test-suite`
    * `alonzo/impl` -> `eras/alonzo/impl`
    * `alonzo/test` -> `eras/alonzo/test-suite`
       (`test-suite` was chosen to avoid confusing  `./alonzo/test/test` path pattern)
    * `byron` -> `eras/byron` (internal structure of byron is left unchanged)
  * Reusable libraries are scattered all over the place. Collected them into a single location and named each folder matching to the package name. Moved:
    * `plutus-preprocessor` -> `libs/plutus-preprocessor`
    * `semantics/executable-spec` -> `libs/small-steps`
    * `semantics/small-steps-test` -> `libs/small-steps-test`
    * `example-shelley` -> `libs/cardano-ledger-example-shelley`
    * `shelley/chain-and-ledger/dependencies/non-integer` -> `libs/non-integral`
    * `cardano-ledger-core` -> `libs/cardano-ledger-core`
    * `cardano-ledger-test` -> `libs/cardano-ledger-test`
    * `cardano-protocol-tpraos` -> `libs/cardano-protocol-tpraos`
* [x] Source files are consistently located across repos in `src`, instead of `lib`. Renamed:
    * Rename `alonzo/test-suite/lib` -> `eras/alonzo/test-suite/src`
* [x] Rename packages for consistency:
    * `shelley-spec-ledger` - > `cardano-ledger-shelley`
    * `shelley-spec-ledger-test` - > `cardano-ledger-shelley-test`
    * `shelley-spec-non-integral` -> `non-integral`
* [x] Create packages that reexport modules from newly named packages with deprecations:
    * `shelley-spec-ledger`
    * `shelley-spec-ledger-test`
    * `shelley-spec-non-integral`

## Formal spec

* [x] Move all era dependent spec into `eras/<era-name>/formal-spec`:
   * `alonzo/formal-spec` -> `eras/alonzo/formal-spec`
   * `shelley-ma/formal-spec` -> `eras/shelley-ma/formal-spec`
   * `shelley/chain-and-ledger/formal-spec` -> `eras/shelley/formal-spec`
   * `shelley/design-spec` -> `eras/shelley/design-spec`
* [x] Move spec for individual packages into `docs/` directory:
   * `shelley/chain-and-ledger/dependencies/non-integer` -> `docs/non-integral-calculations`
   * `semantics/formal-spec` -> `docs/small-step-semantics`
   * `shelley/pool-ranking` -> `docs/pool-ranking`

## Create symlinks

In order to minimize downstream breakage, at least initially, we should create symbolic links for all moved projects:

* [x] - Create symlinks for:
    * `alonzo` -> `eras/alonzo`
    * `alonzo/test` -> `eras/alonzo/test-suite`
    * `byron` -> `eras/byron`
    * `shelley` -> `eras/shelley`
    * `shelley/pool-ranking` -> `docs/pool-ranking`
    * `shelley/chain-and-ledger/formal-spec` -> `eras/shelley/formal-spec`
    * `shelley/chain-and-ledger/dependencies/non-integer/doc` -> `docs/non-integer-calculations`
    * `shelley-ma` -> `eras/shelley-ma`
    * `shelley-ma/shelley-ma-test` -> `eras/shelley-ma/test-suite`
    * `semantics/executable-spec` -> `libs/small-steps`
    * `semantics/formal-spec` -> `docs/small-step-semantics`
    * `semantics/small-steps-test` -> `libs/small-steps-test`
    * `cardano-ledger-core` -> `libs/cardano-ledger-core`
    * `cardano-ledger-test` -> `libs/cardano-ledger-test`
    * `cardano-protocol-tpraos` -> `libs/cardano-protocol-tpraos`
    * `example-shelley` -> `libs/cardano-ledger-example-shelley`
    * `plutus-preprocessor` -> `libs/plutus-preprocessor`

## Readme

* [x] - Update readme to reflect new locations

## Repository name

* `cardano-ledger-spec` -> `cardano-ledger` - we can do it immediately and everything will work, because github will take care of redirection. However, if I'll be updating upstream repos anyways it will make sense for me to make that change upstream as well.

### CODE REVIEW

**Comment by nc6** [comment]
I think this is great! Thanks for actually pushing on it.

```
semantics/small-step-test -> libraries/small-step-test
```
Should this not go to `libraries/small-steps/test-suite`?

```
cardano-ledger-core -> libraries/cardano-ledger-core
cardano-ledger-test -> libraries/cardano-ledger-test
cardano-protocol-tpraos -> libraries/cardano-protocol-tpraos
```

I would argue that these things aren't really "shared libraries" in the same sense and should stay in the top level dir. Unless you do intend to move everything into `libraries`. I think I'm slightly _against_ that plan, but it's a very weak preference.

**Comment by lehins** [comment]
> Should this not go to libraries/small-steps/test-suite?

No, that would be inconsistent. However, something like this would be, I think:

* libraries/small-steps/impl
* libraries/small-steps/test-suite

So, I could change that, but there was some feedback on slack and I also suggested in this PR to move all Haskell packages into `libraries` and name their paths the same way the packages are named. This would be consistent with other repositories in the `input-output-hk` organization and in Haskell in general. You said that you are slightly against it, but it is really hard for people to find those packages in the repo. I had to constantly look into `cabal.project` and grep the repo, until I finally learned where all the packages are.

> I would argue that these things aren't really "shared libraries" in the same sense and should stay in the top level dir. 

I think consistency is more important than conceptual organization. We don't want to require a person to know what the library is for in order to locate it. If we had hundreds of libraries in this repo, then organizing them by the topic or something would be logical, but having 14 packages now spread throughout the repo is suboptimal IMHO. We could of course put all packages at the top level, but considering we have all sorts of other non-Haskell stuff it would be a little busy. 

Let's discuss all those things tomorrow during our meeting and we can reach consensus all together on all the naming/placement.

**Comment by JaredCorduan** [comment]
Thank you again for taking this on @lehins ! When we are settled on a plan, let's remember to update the [Readme](https://github.com/input-output-hk/cardano-ledger-specs#repository-structure).

**Comment by nc6** [comment]
Aha, yeah, 
```
libraries/small-steps/impl
libraries/small-steps/test-suite
```
Is definitely better!

**Review by JaredCorduan — APPROVED** [review]

**Comment by mark-stopka** [comment]
Sweet, much easier to navigate now!

**Comment by JaredCorduan** [comment]
indeed, many thanks to @lehins for this much needed clean up :raised_hands:

**Pull request merged**
